### ISSUE TITLE
How can you achieve push queue with SQS ?

### ISSUE THREAD

**Issue by tristanbes** [uecode/qpush-bundle#82]
Hi,

Simple question, IronMQ says that they are the only one offering push queues.
How can you achieve that with an SQS endpoint ? Does AWS needs a lot of extra config ?

source: http://www.iron.io/mq/comparison/

**Comment by kmfk** [comment]
SQS by itself does not actually push messages, that's correct.  The work around is to actually publish your message into a SNS topic which you can subscribe both your own endpoints to as well as an SQS queue.

This library abstracts that setup for you. When you use AWS and enable it as a push queue in the settings, it will automatically create the required SNS topic and SQS queue and handle the subscriptions, so that the functionality works as expected.

The subscription confirmation from your endpoints are also handled for you as long as the endpoints are externally accessible - which in a dev environment, you can use [ngrok](https://ngrok.com/) for, if need be.

**Comment by tristanbes** [comment]
great, thanks for the explanation @kmfk 
How the throttling is handled ? In other word,, if by using SNS you manage to do push queues, what prevent the consumer from being spammed/flooded by request. Do the throttling has to be implement by the client ?

I know this is not the subject in here, but between iron and SQS what would you recommand ?

**Comment by kmfk** [comment]
Yeah, throttling right now would be up to the client - though not sure that problem is specific to SNS, but would be an issue with push queues in general.

This library uses the notifications from SNS to avoid the need for polling, but still relies on and fetches the messages off the SQS queue. This provides durability and persistence which should help in the case that you manage to DDoS your servers with an aggressive push queue, so messages aren't lost.

Between the two, IronMQ built support for push queues directly and was more easily implemented in this library. However, when I used Iron, there was quite a few outages which led us to switch to AWS.  That was more than a year ago - so, if their service has become more stable, they'd be my choice - I'd check them out.

Ideally, this library should make either just as easy to work with.

**Comment by tristanbes** [comment]
:+1: thanks for clarification
